import { StyleSheet } from '@react-pdf/renderer';

export const pdfStyles = StyleSheet.create({
  page: { padding: 42, fontSize: 9, color: '#182033', fontFamily: 'Noto Sans KR' },
  header: { marginBottom: 18 },
  name: { fontSize: 26, fontWeight: 700, marginBottom: 5 },
  title: { fontSize: 11, color: '#31506d' },
  contact: { marginTop: 8, color: '#526174' },
  link: { color: '#1468d4', textDecoration: 'none' },
  section: { marginTop: 16 },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 700,
    borderBottomWidth: 1,
    borderBottomColor: '#172033',
    paddingBottom: 4,
    marginBottom: 8,
  },
  text: { lineHeight: 1.45 },
  career: {
    marginBottom: 22,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#d5dbe3',
  },
  careerHead: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 3 },
  careerName: { fontWeight: 700 },
  muted: { color: '#667085' },
  project: { marginTop: 6, paddingLeft: 8, borderLeftWidth: 2, borderLeftColor: '#c8d0dc' },
  projectName: { fontWeight: 700 },
  pills: { flexDirection: 'row', flexWrap: 'wrap', gap: 4 },
  pill: {
    borderWidth: 1,
    borderColor: '#c8d0dc',
    borderRadius: 3,
    padding: 4,
    marginRight: 4,
    marginBottom: 4,
  },
  panelPage: { padding: 0, fontFamily: 'Noto Sans KR' },
  panelLayout: { flexDirection: 'row', width: '100%' },
  panel: { width: '30%', backgroundColor: '#eef2f6', padding: 25 },
  panelBody: { width: '70%', padding: 30 },
  timeline: { borderLeftWidth: 2, borderLeftColor: '#b8c3d1', paddingLeft: 10 },
  timelineItem: {
    marginBottom: 22,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#d5dbe3',
  },
  compactHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 2,
    paddingBottom: 8,
  },
});
